name: Build, Push to GHCR and Deploy

on:
  push:
    branches: [main]

env:
  IMAGE_NAME: bayview-workshop
  REGISTRY: ghcr.io
  IMAGE_TAG: latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Login no GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build da imagem Docker
      run: |
        docker build -t ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .

    - name: Push da imagem para GHCR
      run: |
        docker push ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
        
    - name: Dispara webhook de deploy no Dokploy da vps secundaria
      run: |
        curl -X POST "${{ secrets.DOKPLOY_WEBHOOK_URL }}"
